
namespace Edubase.Data.Entity.Lookups
{
    public enum eLookupReligiousEthos
    {
        Anglican = 1,
		Anglicanchristian = 2,
		AnglicanchurchOfEngland = 3,
		Anglicanevangelical = 4,
		Buddhist = 5,
		Catholic = 6,
		CharadiJewish = 7,
		Christian = 8,
		ChristianScience = 9,
		Christianevangelical = 10,
		Christianmethodist = 11,
		Christiannondenominational = 12,
		ChurchOfEngland = 13,
		ChurchOfEnglandchristian = 14,
		ChurchOfEnglandevangelical = 15,
		ChurchOfEnglandfreeChurch = 16,
		ChurchOfEnglandmethodist = 17,
		ChurchOfEnglandmethodistunitedReformChurchbaptist = 18,
		ChurchOfEnglandromanCatholic = 19,
		ChurchOfEnglandunitedReformedChurch = 20,
		CongregationalChurch = 21,
		DoesNotApply = 22,
		FreeChurch = 23,
		GreekOrthodox = 24,
		Hindu = 25,
		InterNonDenominational = 26,
		Islam = 27,
		Jewish = 28,
		Methodist = 29,
		MethodistchurchOfEngland = 30,
		Moravian = 31,
		Multifaith = 32,
		Muslim = 33,
		None = 34,
		OrthodoxJewish = 35,
		Pentecostal = 36,
		PlymouthBrethrenChristianChurch = 37,
		Protestant = 38,
		Protestantevangelical = 39,
		Quaker = 40,
		ReformedBaptist = 41,
		RomanCatholic = 42,
		RomanCatholicanglican = 43,
		RomanCatholicchurchOfEngland = 44,
		SeventhDayAdventist = 45,
		Sikh = 46,
		SunniDeobandi = 47,
		Unitarian = 48,
		UnitedReformedChurch = 49,
		Unknown = 50,
    }
}   
