
namespace Edubase.Services.Enums
{
    public enum eLookupEstablishmentType
    {
        Academy1619Converter = 39,
        Academy1619SponsorLed = 40,
        AcademyAlternativeProvisionConverter = 36,
        AcademyAlternativeProvisionSponsorLed = 37,
        AcademyConverter = 28,
        AcademySpecialConverter = 38,
        AcademySpecialSponsorLed = 27,
        AcademySponsorLed = 22,
        BritishSchoolsOverseas = 31,
        ChildrensCentre = 41,
        ChildrensCentreLinkedSite = 42,
        CityTechnologyCollege = 5,
        CommunitySchool = 1,
        CommunitySpecialSchool = 6,
        EuropeanSchools = 14,
        EYSetting = 16,
        FoundationSchool = 4,
        FoundationSpecialSchool = 11,
        FreeSchools = 29,
        FreeSchools1619 = 33,
        FreeSchoolsAlternativeProvision = 32,
        FreeSchoolsSpecial = 30,
        FurtherEducation = 15,
        HigherEducationInstitutions = 23,
        IndependentSchoolApprovedForSENPupils = 8,
        InstitutionFundedByOtherGovernmentDepartment = 43,
        LANurserySchool = 13,
        LegacyTypes = 44,
        Miscellaneous = 21,
        NonmaintainedSpecialSchool = 7,
        OffshoreSchools = 19,
        OtherIndependentSchool = 10,
        OtherIndependentSpecialSchool = 9,
        PlayingForSuccessCentres = 17,
        PupilReferralUnit = 12,
        SecureUnits = 18,
        ServiceChildrensEducation = 20,
        SixthFormCentres = 25,
        SpecialPost16Institution = 26,
        StudioSchools = 35,
        UniversityTechnicalCollege = 34,
        VoluntaryAidedSchool = 2,
        VoluntaryControlledSchool = 3,
        WelshEstablishment = 24,
        OnlineProvider = 45,
        AcademySecure16to19 = 46
    }
}   
