
namespace Edubase.Services.Enums
{
#if (TEXAPI)
    public enum eLookupEstablishmentType
    {
        Academy1619Converter = 39,
        Academy1619SponsorLed = 40,
        AcademyAlternativeProvisionConverter = 36,
        AcademyAlternativeProvisionSponsorLed = 37,
        AcademyConverter = 28,
        AcademySpecialConverter = 38,
        AcademySpecialSponsorLed = 27,
        AcademySponsorLed = 22,
        BritishSchoolsOverseas = 31,
        ChildrensCentre = 41,
        ChildrensCentreLinkedSite = 42,
        CityTechnologyCollege = 5,
        CommunitySchool = 1,
        CommunitySpecialSchool = 6,
        EuropeanSchools = 14,
        EYSetting = 16,
        FoundationSchool = 4,
        FoundationSpecialSchool = 11,
        FreeSchools = 29,
        FreeSchools1619 = 33,
        FreeSchoolsAlternativeProvision = 32,
        FreeSchoolsSpecial = 30,
        FurtherEducation = 15,
        HigherEducationInstitutions = 23,
        IndependentSchoolApprovedForSENPupils = 8,
        InstitutionFundedByOtherGovernmentDepartment = 43,
        LANurserySchool = 13,
        LegacyTypes = 44,
        Miscellaneous = 21,
        NonmaintainedSpecialSchool = 7,
        OffshoreSchools = 19,
        OtherIndependentSchool = 10,
        OtherIndependentSpecialSchool = 9,
        PlayingForSuccessCentres = 17,
        PupilReferralUnit = 12,
        SecureUnits = 18,
        ServiceChildrensEducation = 20,
        SixthFormCentres = 25,
        SpecialPost16Institution = 26,
        StudioSchools = 35,
        UniversityTechnicalCollege = 34,
        VoluntaryAidedSchool = 2,
        VoluntaryControlledSchool = 3,
        WelshEstablishment = 24,
    }
#else
    public enum eLookupEstablishmentType
    {
        Academy1619Converter = 1,
		Academy1619SponsorLed = 2,
		AcademyAlternativeProvisionConverter = 3,
		AcademyAlternativeProvisionSponsorLed = 4,
		AcademyConverter = 5,
		AcademySpecialConverter = 6,
		AcademySpecialSponsorLed = 7,
		AcademySponsorLed = 8,
		BritishSchoolsOverseas = 9,
		ChildrensCentre = 10,
		ChildrensCentreLinkedSite = 11,
		CityTechnologyCollege = 12,
		CommunitySchool = 13,
		CommunitySpecialSchool = 14,
		FoundationSchool = 17,
		FoundationSpecialSchool = 18,
		FreeSchools = 19,
		FreeSchools1619 = 20,
		FreeSchoolsAlternativeProvision = 21,
		FreeSchoolsSpecial = 22,
		FurtherEducation = 23,
		HigherEducationInstitutions = 24,
		InstitutionFundedByOtherGovernmentDepartment = 26,
		LANurserySchool = 27,
		Miscellaneous = 29,
		NonmaintainedSpecialSchool = 30,
		OffshoreSchools = 31,
		OtherIndependentSchool = 32,
		OtherIndependentSpecialSchool = 33,
		PupilReferralUnit = 35,
		SecureUnits = 36,
		ServiceChildrensEducation = 37,
		SixthFormCentres = 38,
		SpecialPost16Institution = 39,
		StudioSchools = 40,
		UniversityTechnicalCollege = 41,
		VoluntaryAidedSchool = 42,
		VoluntaryControlledSchool = 43,
		WelshEstablishment = 44,
    }
#endif
}   
