using System.Collections.Generic;
using System.Threading.Tasks;
using Edubase.Services.Domain;

namespace Edubase.Services.Lookup
{
    public interface ILookupService
    {
        Task<IEnumerable<LookupDto>> AccommodationChangedGetAllAsync();
        Task<IEnumerable<LookupDto>> AdministrativeDistrictsGetAllAsync();
        Task<IEnumerable<LookupDto>> AdministrativeWardsGetAllAsync();
        Task<IEnumerable<LookupDto>> AdmissionsPoliciesGetAllAsync();
        Task<IEnumerable<LookupDto>> BoardingEstablishmentGetAllAsync();
        Task<IEnumerable<LookupDto>> CCDeliveryModelsGetAllAsync();
        Task<IEnumerable<LookupDto>> CCDisadvantagedAreasGetAllAsync();
        Task<IEnumerable<LookupDto>> CCGovernanceGetAllAsync();
        Task<IEnumerable<LookupDto>> CCGroupLeadsGetAllAsync();
        Task<IEnumerable<LookupDto>> CCOperationalHoursGetAllAsync();
        Task<IEnumerable<LookupDto>> CCPhaseTypesGetAllAsync();
        Task<IEnumerable<LookupDto>> ChildcareFacilitiesGetAllAsync();
        Task<IEnumerable<LookupDto>> DiocesesGetAllAsync();
        Task<IEnumerable<LookupDto>> DirectProvisionOfEarlyYearsGetAllAsync();
        Task<IEnumerable<LookupDto>> EducationPhasesGetAllAsync();
        Task<IEnumerable<LookupDto>> EstablishmentAccreditedGetAllAsync();
        Task<IEnumerable<LookupDto>> EstablishmentLinkTypesGetAllAsync();
        Task<IEnumerable<LookupDto>> EstablishmentStatusesGetAllAsync();
        Task<IEnumerable<LookupDto>> EstablishmentTypeGroupsGetAllAsync();
        Task<IEnumerable<EstablishmentLookupDto>> EstablishmentTypesGetAllAsync();
        Task<IEnumerable<LookupDto>> FurtherEducationTypesGetAllAsync();
        Task<IEnumerable<LookupDto>> GendersGetAllAsync();
        Task<IEnumerable<LookupDto>> GovernmentOfficeRegionsGetAllAsync();
        Task<IEnumerable<LookupDto>> GovernorAppointingBodiesGetAllAsync();
        Task<IEnumerable<LookupDto>> GovernorRolesGetAllAsync();
        Task<IEnumerable<LookupDto>> GroupStatusesGetAllAsync();
        Task<IEnumerable<LookupDto>> GroupTypesGetAllAsync();
        Task<IEnumerable<LookupDto>> GSSLAGetAllAsync();
        Task<IEnumerable<LookupDto>> TitlesGetAllAsync();
        Task<IEnumerable<LookupDto>> IndependentSchoolTypesGetAllAsync();
        Task<IEnumerable<LookupDto>> InspectorateNamesGetAllAsync();
        Task<IEnumerable<LookupDto>> InspectoratesGetAllAsync();
        Task<IEnumerable<LookupDto>> LocalAuthorityGetAllAsync();
        Task<IEnumerable<LookupDto>> LocalGovernorsGetAllAsync();
        Task<IEnumerable<LookupDto>> LSOAsGetAllAsync();
        Task<IEnumerable<LookupDto>> MSOAsGetAllAsync();
        Task<IEnumerable<LookupDto>> NationalitiesGetAllAsync();
        Task<IEnumerable<LookupDto>> ParliamentaryConstituenciesGetAllAsync();
        Task<IEnumerable<LookupDto>> ProvisionBoardingGetAllAsync();
        Task<IEnumerable<LookupDto>> ProvisionNurseriesGetAllAsync();
        Task<IEnumerable<LookupDto>> ProvisionOfficialSixthFormsGetAllAsync();
        Task<IEnumerable<LookupDto>> ProvisionSpecialClassesGetAllAsync();
        Task<IEnumerable<LookupDto>> PRUEBDsGetAllAsync();
        Task<IEnumerable<LookupDto>> PruEducatedByOthersGetAllAsync();
        Task<IEnumerable<LookupDto>> PruFulltimeProvisionsGetAllAsync();
        Task<IEnumerable<LookupDto>> PRUSENsGetAllAsync();
        Task<IEnumerable<LookupDto>> QualityAssuranceBodyNameGetAllAsync();
        Task<IEnumerable<LookupDto>> ReasonEstablishmentClosedGetAllAsync();
        Task<IEnumerable<LookupDto>> ReasonEstablishmentOpenedGetAllAsync();
        Task<IEnumerable<LookupDto>> ReligiousCharactersGetAllAsync();
        Task<IEnumerable<LookupDto>> ReligiousEthosGetAllAsync();
        Task<IEnumerable<LookupDto>> ResourcedProvisionsGetAllAsync();
        Task<IEnumerable<LookupDto>> Section41ApprovedGetAllAsync();
        Task<IEnumerable<LookupDto>> SpecialEducationNeedsGetAllAsync();
        Task<IEnumerable<LookupDto>> TeenageMothersProvisionsGetAllAsync();
        Task<IEnumerable<LookupDto>> TypeOfResourcedProvisionsGetAllAsync();
        Task<IEnumerable<LookupDto>> UrbanRuralGetAllAsync();
        Task<IEnumerable<LookupDto>> CountiesGetAllAsync();
        Task<IEnumerable<LookupDto>> OfstedRatingsGetAllAsync();
        Task<IEnumerable<LookupDto>> RscRegionsGetAllAsync();
    }
}
