parameters:

  # Runner and job/step settings
  - name: enabled
    default: 'true'
  - name: vmImage
    default: 'windows-latest'

  # Naming settings
  - name: thisJobName

  # Build and deploy settings
  - name: version
  - name: artifactReference
    default: 'BuiltAndPackagedWebUiZip'


jobs:

  - job: ${{ parameters.thisJobName }}
    displayName: Build, Test, and Package - ${{ parameters.thisJobName }}
    condition: eq(${{ parameters.enabled }}, 'true')
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      solution: 'Web/EdubaseWeb.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      BRANCH_NAME: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
      BRANCH_NAME_NORMALISED: $[replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), '/', '_')]

    steps:

      - task: PowerShell@2
        displayName: Display variables
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "Variables:"
            Write-Host "- BRANCH_NAME: $(BRANCH_NAME)"
            Write-Host "- BRANCH_NAME_NORMALISED: $(BRANCH_NAME_NORMALISED)"
            Write-Host "- solution: $(solution)"
            Write-Host "- buildPlatform: $(buildPlatform)"
            Write-Host "- buildConfiguration: $(buildConfiguration)"

      - checkout: self
        submodules: recursive

      - task: PowerShell@2
        displayName: Version assemblies
        inputs:
          targetType: 'inline'
          script: |
            $version = "$(version)"
            Write-Host "Version: $version"
            $Env:BUILD_BUILDNUMBER="$version"
            $Env:BUILD_SOURCESDIRECTORY="$(Build.SourcesDirectory)"
            Write-Host "BUILD_BUILDNUMBER: $($Env:BUILD_BUILDNUMBER)"
            Write-Host "BUILD_SOURCESDIRECTORY: $($Env:BUILD_SOURCESDIRECTORY)"
            $(Build.SourcesDirectory)/ApplyVersionToAssemblies.ps1

      ## Ensure correct .NET SDK
      - task: UseDotNet@2
        displayName: 'Install .NET 8 SDK'
        inputs:
          packageType: 'sdk'
          version: '8.0.x'

      ## BUILD THE WEB UI JAVASCRIPT/WEBPACK BITS
      - task: NodeTool@0
        displayName: 'Install Node.js 18.x'
        inputs:
          versionSource: 'spec'
          versionSpec: '18.x'

      - task: Npm@1
        displayName: 'Install NPM dependencies (Web UI)'
        inputs:
          command: 'ci'
          workingDir: 'Web/Edubase.Web.UI'

      - task: Npm@1
        displayName: 'Build Web UI (webpack)'
        inputs:
          command: 'custom'
          workingDir: 'Web/Edubase.Web.UI'
          customCommand: 'run buildCi'

      ## BUILD AND TEST THE C# CODE USING DOTNET CLI
      - task: DotNetCoreCLI@2
        displayName: Restore .NET solution
        inputs:
          command: restore
          projects: '$(solution)'

      - task: DotNetCoreCLI@2
        displayName: Build .NET solution
        inputs:
          command: build
          projects: '$(solution)'
          arguments: '--configuration $(buildConfiguration)'

      - task: DotNetCoreCLI@2
        displayName: Run C# tests with coverage
        inputs:
          command: test
          projects: '**/*UnitTests.csproj'
          arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage"'

      - task: PublishCodeCoverageResults@1
        displayName: Publish coverage results
        inputs:
          codeCoverageTool: 'Cobertura'
          summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'
          reportDirectory: '$(Build.SourcesDirectory)/**/TestResults'
          failIfCoverageEmpty: true

      - task: CmdLine@2
        displayName: File listing - artifact staging dir - $(build.artifactstagingdirectory)
        inputs:
          script: |
            tree $(build.artifactstagingdirectory)
            dir $(build.artifactstagingdirectory)

      - publish: '$(build.artifactstagingdirectory)/Edubase.Web.UI.zip'
        artifact: ${{ parameters.artifactReference }}
        displayName: Attach packaged Web UI to pipeline run
