parameters:

  # Runner and job/step settings
  - name: enabled
    default: 'true'
  - name: vmImage
    default: 'windows-latest'  ## Uses .NET Framework, therefore must use Windows runner

  # Naming settings
  - name: thisJobName

  # Build and deploy settings
  - name: version
  - name: artifactReference
    default: 'BuiltAndPackagedWebUiZip'


jobs:

  - job: ${{ parameters.thisJobName }}
    displayName: Build, Test, and Package - ${{ parameters.thisJobName }}
    condition: eq(${{ parameters.enabled }}, 'true')
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      solution: 'Web/Edubase.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      BRANCH_NAME: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
      BRANCH_NAME_NORMALISED: $[replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), '/', '_')]

    steps:

      ## Debugging assistance task - display all variables and parameters
      - task: PowerShell@2
        displayName: Display variables
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "Variables:"
            Write-Host "- BRANCH_NAME: $(BRANCH_NAME)"
            Write-Host "- BRANCH_NAME_NORMALISED: $(BRANCH_NAME_NORMALISED)"
            Write-Host "- solution: $(solution)"
            Write-Host "- buildPlatform: $(buildPlatform)"
            Write-Host "- buildConfiguration: $(buildConfiguration)"

      - task: PowerShell@2
        displayName: Display parameters
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "Parameters:"
            Write-Host "- enabled: ${{ parameters.enabled }}"
            Write-Host "- vmImage: ${{ parameters.vmImage }}"
            Write-Host "- thisJobName: ${{ parameters.thisJobName }}"

      - checkout: self
        submodules: recursive

      - task: PowerShell@2
        displayName: Version assemblies
        inputs:
          targetType: 'inline'
          script: |
            $version = "$(version)"
            Write-Host "Version: $version"
            $Env:BUILD_BUILDNUMBER="$version"
            $Env:BUILD_SOURCESDIRECTORY="$(Build.SourcesDirectory)"
            Write-Host "BUILD_BUILDNUMBER: $($Env:BUILD_BUILDNUMBER)"
            Write-Host "BUILD_SOURCESDIRECTORY: $($Env:BUILD_SOURCESDIRECTORY)"
            $(Build.SourcesDirectory)/ApplyVersionToAssemblies.ps1

      ## BUILD THE WEB UI JAVASCRIPT/WEBPACK BITS
      - task: NodeTool@0
        displayName: 'Install Node.js 18.x'
        inputs:
          versionSource: 'spec'
          versionSpec: '18.x'

      - task: Npm@1
        displayName: 'Install NPM dependencies (Web UI)'
        inputs:
          command: 'ci'
          workingDir: 'Web/Edubase.Web.UI'

      - task: Npm@1
        displayName: 'Build Web UI (webpack)'
        inputs:
          command: 'custom'
          workingDir: 'Web/Edubase.Web.UI'
          customCommand: 'run buildCi'

      ## BUILD AND TEST THE C# CODE
      - task: NuGetToolInstaller@1
        displayName: 'Install NuGet'

      - task: NuGetCommand@2
        displayName: Restore C# solution
        inputs:
          restoreSolution: '$(solution)'

      - task: VSBuild@1
        displayName: Build C# solution
        inputs:
          solution: '$(solution)'
          msbuildArgs: /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\" /p:PrecompileBeforePublish=true /p:RunCodeAnalysis=false
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

      - task: VSTest@2
        displayName: Run C# tests with coverage
        inputs:
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          testAssemblyVer2: |
            **\*UnitTests.dll
            !**\obj\**
          codeCoverageEnabled: true
          runSettingsFile: 'coverlet.runsettings'
          diagnosticsEnabled: true

      - task: PublishCodeCoverageResults@1
        displayName: Publish coverage results
        inputs:
          codeCoverageTool: 'Cobertura'
          summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
          reportDirectory: '$(Agent.TempDirectory)/**'
          failIfCoverageEmpty: true

      ## Display content listing of the artifact staging directory
      - task: CmdLine@2
        displayName: File listing - artifact staging dir - $(build.artifactstagingdirectory)
        inputs:
          script: |
            tree $(build.artifactstagingdirectory)
            dir $(build.artifactstagingdirectory)

      ## PACKAGE THE WEB UI READY FOR DEPLOYMENT
      - publish: '$(build.artifactstagingdirectory)/Edubase.Web.UI.zip'
        artifact: ${{ parameters.artifactReference }}
        displayName: Attach packaged Web UI to pipeline run
