[{ "value": "0", "label": "Does not apply" },
{ "value": "201", "label": "City of London" },
{ "value": "202", "label": "Camden" },
{ "value": "203", "label": "Greenwich" },
{ "value": "204", "label": "Hackney" },
{ "value": "205", "label": "Hammersmith and Fulham" },
{ "value": "206", "label": "Islington" },
{ "value": "207", "label": "Kensington and Chelsea" },
{ "value": "208", "label": "Lambeth" },
{ "value": "209", "label": "Lewisham" },
{ "value": "210", "label": "Southwark" },
{ "value": "211", "label": "Tower Hamlets" },
{ "value": "212", "label": "Wandsworth" },
{ "value": "213", "label": "Westminster" },
{ "value": "301", "label": "Barking and Dagenham" },
{ "value": "302", "label": "Barnet" },
{ "value": "303", "label": "Bexley" },
{ "value": "304", "label": "Brent" },
{ "value": "305", "label": "Bromley" },
{ "value": "306", "label": "Croydon" },
{ "value": "307", "label": "Ealing" },
{ "value": "308", "label": "Enfield" },
{ "value": "309", "label": "Haringey" },
{ "value": "310", "label": "Harrow" },
{ "value": "311", "label": "Havering" },
{ "value": "312", "label": "Hillingdon" },
{ "value": "313", "label": "Hounslow" },
{ "value": "314", "label": "Kingston upon Thames" },
{ "value": "315", "label": "Merton" },
{ "value": "316", "label": "Newham" },
{ "value": "317", "label": "Redbridge" },
{ "value": "318", "label": "Richmond upon Thames" },
{ "value": "319", "label": "Sutton" },
{ "value": "320", "label": "Waltham Forest" },
{ "value": "330", "label": "Birmingham" },
{ "value": "331", "label": "Coventry" },
{ "value": "332", "label": "Dudley" },
{ "value": "333", "label": "Sandwell" },
{ "value": "334", "label": "Solihull" },
{ "value": "335", "label": "Walsall" },
{ "value": "336", "label": "Wolverhampton" },
{ "value": "340", "label": "Knowsley" },
{ "value": "341", "label": "Liverpool" },
{ "value": "342", "label": "St. Helens" },
{ "value": "343", "label": "Sefton" },
{ "value": "344", "label": "Wirral" },
{ "value": "350", "label": "Bolton" },
{ "value": "351", "label": "Bury" },
{ "value": "352", "label": "Manchester" },
{ "value": "353", "label": "Oldham" },
{ "value": "354", "label": "Rochdale" },
{ "value": "355", "label": "Salford" },
{ "value": "356", "label": "Stockport" },
{ "value": "357", "label": "Tameside" },
{ "value": "358", "label": "Trafford" },
{ "value": "359", "label": "Wigan" },
{ "value": "370", "label": "Barnsley" },
{ "value": "371", "label": "Doncaster" },
{ "value": "372", "label": "Rotherham" },
{ "value": "373", "label": "Sheffield" },
{ "value": "380", "label": "Bradford" },
{ "value": "381", "label": "Calderdale" },
{ "value": "382", "label": "Kirklees" },
{ "value": "383", "label": "Leeds" },
{ "value": "384", "label": "Wakefield" },
{ "value": "390", "label": "Gateshead" },
{ "value": "391", "label": "Newcastle upon Tyne" },
{ "value": "392", "label": "North Tyneside" },
{ "value": "393", "label": "South Tyneside" },
{ "value": "394", "label": "Sunderland" },
{ "value": "420", "label": "Isles Of Scilly" },
{ "value": "660", "label": "Isle of Anglesey" },
{ "value": "661", "label": "Gwynedd" },
{ "value": "662", "label": "Conwy" },
{ "value": "663", "label": "Denbighshire" },
{ "value": "664", "label": "Flintshire" },
{ "value": "665", "label": "Wrexham" },
{ "value": "666", "label": "Powys" },
{ "value": "667", "label": "Ceredigion" },
{ "value": "668", "label": "Pembrokeshire" },
{ "value": "669", "label": "Carmarthenshire" },
{ "value": "670", "label": "Swansea" },
{ "value": "671", "label": "Neath Port Talbot" },
{ "value": "672", "label": "Bridgend" },
{ "value": "673", "label": "The Vale of Glamorgan" },
{ "value": "674", "label": "Rhondda, Cynon, Taff" },
{ "value": "675", "label": "Merthyr Tydfil" },
{ "value": "676", "label": "Caerphilly" },
{ "value": "677", "label": "Blaenau Gwent" },
{ "value": "678", "label": "Torfaen" },
{ "value": "679", "label": "Monmouthshire" },
{ "value": "680", "label": "Newport" },
{ "value": "681", "label": "Cardiff" },
{ "value": "701", "label": "Scotland Offshore Establishments" },
{ "value": "702", "label": "BFPO Overseas Establishments" },
{ "value": "703", "label": "British Overseas Establishments" },
{ "value": "704", "label": "Fieldwork Overseas Establishments" },
{ "value": "705", "label": "Isle of Man Offshore Establishments" },
{ "value": "706", "label": "Guernsey Offshore Establishments" },
{ "value": "707", "label": "Jersey Offshore Establishments" },
{ "value": "708", "label": "Gibraltar Overseas Establishments" },
{ "value": "800", "label": "Bath and North East Somerset" },
{ "value": "801", "label": "Bristol City of" },
{ "value": "802", "label": "North Somerset" },
{ "value": "803", "label": "South Gloucestershire" },
{ "value": "805", "label": "Hartlepool" },
{ "value": "806", "label": "Middlesbrough" },
{ "value": "807", "label": "Redcar and Cleveland" },
{ "value": "808", "label": "Stockton-on-Tees" },
{ "value": "810", "label": "Kingston upon Hull City of" },
{ "value": "811", "label": "East Riding of Yorkshire" },
{ "value": "812", "label": "North East Lincolnshire" },
{ "value": "813", "label": "North Lincolnshire" },
{ "value": "815", "label": "North Yorkshire" },
{ "value": "816", "label": "York" },
{ "value": "820", "label": "Pre LGR (2009) Bedfordshire" },
{ "value": "821", "label": "Luton" },
{ "value": "822", "label": "Bedford" },
{ "value": "823", "label": "Central Bedfordshire" },
{ "value": "825", "label": "Buckinghamshire" },
{ "value": "826", "label": "Milton Keynes" },
{ "value": "830", "label": "Derbyshire" },
{ "value": "831", "label": "Derby" },
{ "value": "835", "label": "Dorset" },
{ "value": "836", "label": "Poole" },
{ "value": "837", "label": "Bournemouth" },
{ "value": "840", "label": "Durham" },
{ "value": "841", "label": "Darlington" },
{ "value": "845", "label": "East Sussex" },
{ "value": "846", "label": "Brighton and Hove" },
{ "value": "850", "label": "Hampshire" },
{ "value": "851", "label": "Portsmouth" },
{ "value": "852", "label": "Southampton" },
{ "value": "855", "label": "Leicestershire" },
{ "value": "856", "label": "Leicester" },
{ "value": "857", "label": "Rutland" },
{ "value": "860", "label": "Staffordshire" },
{ "value": "861", "label": "Stoke-on-Trent" },
{ "value": "865", "label": "Wiltshire" },
{ "value": "866", "label": "Swindon" },
{ "value": "867", "label": "Bracknell Forest" },
{ "value": "868", "label": "Windsor and Maidenhead" },
{ "value": "869", "label": "West Berkshire" },
{ "value": "870", "label": "Reading" },
{ "value": "871", "label": "Slough" },
{ "value": "872", "label": "Wokingham" },
{ "value": "873", "label": "Cambridgeshire" },
{ "value": "874", "label": "Peterborough" },
{ "value": "875", "label": "Pre LGR (2009) Cheshire" },
{ "value": "876", "label": "Halton" },
{ "value": "877", "label": "Warrington" },
{ "value": "878", "label": "Devon" },
{ "value": "879", "label": "Plymouth" },
{ "value": "880", "label": "Torbay" },
{ "value": "881", "label": "Essex" },
{ "value": "882", "label": "Southend-on-Sea" },
{ "value": "883", "label": "Thurrock" },
{ "value": "884", "label": "Herefordshire" },
{ "value": "885", "label": "Worcestershire" },
{ "value": "886", "label": "Kent" },
{ "value": "887", "label": "Medway" },
{ "value": "888", "label": "Lancashire" },
{ "value": "889", "label": "Blackburn with Darwen" },
{ "value": "890", "label": "Blackpool" },
{ "value": "891", "label": "Nottinghamshire" },
{ "value": "892", "label": "Nottingham" },
{ "value": "893", "label": "Shropshire" },
{ "value": "894", "label": "Telford and Wrekin" },
{ "value": "895", "label": "Cheshire East" },
{ "value": "896", "label": "Cheshire West and Chester" },
{ "value": "901", "label": "Pre LGR (1996) Avon" },
{ "value": "902", "label": "Pre LGR (1997) Bedfordshire" },
{ "value": "903", "label": "Pre LGR (1998) Berkshire" },
{ "value": "904", "label": "Pre LGR (1997) Buckinghamshire" },
{ "value": "905", "label": "Pre LGR (1998) Cambridgeshire" },
{ "value": "906", "label": "Pre LGR (1998) Cheshire" },
{ "value": "907", "label": "Pre LGR (1996) Cleveland" },
{ "value": "908", "label": "Cornwall" },
{ "value": "909", "label": "Cumbria" },
{ "value": "910", "label": "Pre LGR (1997) Derbyshire" },
{ "value": "911", "label": "Pre LGR (1998) Devon" },
{ "value": "912", "label": "Pre LGR (1997) Dorset" },
{ "value": "913", "label": "Pre LGR (1997) Durham" },
{ "value": "914", "label": "Pre LGR (1997) East Sussex" },
{ "value": "915", "label": "Pre LGR (1998) Essex" },
{ "value": "916", "label": "Gloucestershire" },
{ "value": "917", "label": "Pre LGR (1997) Hampshire" },
{ "value": "918", "label": "Pre LGR (1998) Hereford & Worcester" },
{ "value": "919", "label": "Hertfordshire" },
{ "value": "920", "label": "Pre LGR (1996) Humberside" },
{ "value": "921", "label": "Isle of Wight" },
{ "value": "922", "label": "Pre LGR (1998) Kent" },
{ "value": "923", "label": "Pre LGR (1998) Lancashire" },
{ "value": "924", "label": "Pre LGR (1997) Leicestershire" },
{ "value": "925", "label": "Lincolnshire" },
{ "value": "926", "label": "Norfolk" },
{ "value": "927", "label": "Pre LGR (1996) North Yorkshire" },
{ "value": "928", "label": "Northamptonshire" },
{ "value": "929", "label": "Northumberland" },
{ "value": "930", "label": "Pre LGR (1998) Nottinghamshire" },
{ "value": "931", "label": "Oxfordshire" },
{ "value": "932", "label": "Pre LGR (1998) Shropshire" },
{ "value": "933", "label": "Somerset" },
{ "value": "934", "label": "Pre LGR (1997) Staffordshire" },
{ "value": "935", "label": "Suffolk" },
{ "value": "936", "label": "Surrey" },
{ "value": "937", "label": "Warwickshire" },
{ "value": "938", "label": "West Sussex" },
{ "value": "939", "label": "Pre LGR (1997) Wiltshire" },
{ "value": "999", "label": "Unknown" }
]
