//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edubase.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FileDownloadNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileDownloadNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Edubase.Web.Resources.FileDownloadNames", typeof(FileDownloadNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAT and MAT membership history CSV.
        /// </summary>
        public static string academies_mat_membership {
            get {
                return ResourceManager.GetString("academies_mat_membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishment additional addresses CSV.
        /// </summary>
        public static string all_edubase_additional_addresses {
            get {
                return ResourceManager.GetString("all_edubase_additional_addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishment fields CSV.
        /// </summary>
        public static string all_edubase_data {
            get {
                return ResourceManager.GetString("all_edubase_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishment links CSV.
        /// </summary>
        public static string all_edubase_data_links {
            get {
                return ResourceManager.GetString("all_edubase_data_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governor ﬁelds CSV.
        /// </summary>
        public static string all_governance_records {
            get {
                return ResourceManager.GetString("all_governance_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academies and free school links CSV.
        /// </summary>
        public static string all_open_academies_and_free_school_links {
            get {
                return ResourceManager.GetString("all_open_academies_and_free_school_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academies and free school ﬁelds CSV.
        /// </summary>
        public static string all_open_academies_and_free_schools {
            get {
                return ResourceManager.GetString("all_open_academies_and_free_schools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children&apos;s centre ﬁelds CSV.
        /// </summary>
        public static string all_open_childrens_centres {
            get {
                return ResourceManager.GetString("all_open_childrens_centres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State-funded school links CSV.
        /// </summary>
        public static string all_open_state_funded_school_links {
            get {
                return ResourceManager.GetString("all_open_state_funded_school_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State-funded school ﬁelds CSV.
        /// </summary>
        public static string all_open_state_funded_schools {
            get {
                return ResourceManager.GetString("all_open_state_funded_schools", resourceCulture);
            }
        }
    }
}
