//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edubase.Import
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EdubaseSourceEntities : DbContext
    {
        public EdubaseSourceEntities()
            : base("name=EdubaseSourceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admissionspolicy> Admissionspolicy { get; set; }
        public virtual DbSet<Boarders> Boarders { get; set; }
        public virtual DbSet<CompanyTable> CompanyTable { get; set; }
        public virtual DbSet<Diocese> Diocese { get; set; }
        public virtual DbSet<Establishmentstatus> Establishmentstatus { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<GroupType> GroupType { get; set; }
        public virtual DbSet<Headtitle> Headtitle { get; set; }
        public virtual DbSet<LocalAuthority> LocalAuthority { get; set; }
        public virtual DbSet<Nurseryprovision> Nurseryprovision { get; set; }
        public virtual DbSet<Officialsixthform> Officialsixthform { get; set; }
        public virtual DbSet<Phaseofeducation> Phaseofeducation { get; set; }
        public virtual DbSet<Reasonestablishmentclosed> Reasonestablishmentclosed { get; set; }
        public virtual DbSet<Reasonestablishmentopened> Reasonestablishmentopened { get; set; }
        public virtual DbSet<Religiouscharacter> Religiouscharacter { get; set; }
        public virtual DbSet<Religiousethos> Religiousethos { get; set; }
        public virtual DbSet<SchoolsTable> SchoolsTable { get; set; }
        public virtual DbSet<SchoolToCompanyLinks> SchoolToCompanyLinks { get; set; }
        public virtual DbSet<SchoolToSchoolLinks> SchoolToSchoolLinks { get; set; }
        public virtual DbSet<Specialclasses> Specialclasses { get; set; }
        public virtual DbSet<Typeofestablishment> Typeofestablishment { get; set; }
    }
}
