//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edubase.Import
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EdubaseSourceEntities : DbContext
    {
        public EdubaseSourceEntities()
            : base("name=EdubaseSourceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admissionspolicy> Admissionspolicies { get; set; }
        public virtual DbSet<Boarder> Boarders { get; set; }
        public virtual DbSet<CompanyTable> CompanyTables { get; set; }
        public virtual DbSet<Diocese> Diocese { get; set; }
        public virtual DbSet<Establishmentstatu> Establishmentstatus { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Governor> Governors { get; set; }
        public virtual DbSet<GroupType> GroupTypes { get; set; }
        public virtual DbSet<Headtitle> Headtitles { get; set; }
        public virtual DbSet<LocalAuthority> LocalAuthorities { get; set; }
        public virtual DbSet<Nurseryprovision> Nurseryprovisions { get; set; }
        public virtual DbSet<Officialsixthform> Officialsixthforms { get; set; }
        public virtual DbSet<Phaseofeducation> Phaseofeducations { get; set; }
        public virtual DbSet<Reasonestablishmentclosed> Reasonestablishmentcloseds { get; set; }
        public virtual DbSet<Reasonestablishmentopened> Reasonestablishmentopeneds { get; set; }
        public virtual DbSet<Religiouscharacter> Religiouscharacters { get; set; }
        public virtual DbSet<Religiousetho> Religiousethos { get; set; }
        public virtual DbSet<SchoolsTable> SchoolsTables { get; set; }
        public virtual DbSet<SchoolToCompanyLink> SchoolToCompanyLinks { get; set; }
        public virtual DbSet<SchoolToSchoolLink> SchoolToSchoolLinks { get; set; }
        public virtual DbSet<Specialclass> Specialclasses { get; set; }
        public virtual DbSet<Typeofestablishment> Typeofestablishments { get; set; }
    }
}
