//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edubase.Import
{
    using System;
    using System.Collections.Generic;
    
    public partial class Governor
    {
        public string URN { get; set; }
        public string GID { get; set; }
        public string Role { get; set; }
        public string Title { get; set; }
        public string Forename1 { get; set; }
        public string Forename2 { get; set; }
        public string Surname { get; set; }
        public string Dateofappointment { get; set; }
        public string Datetermofofficeendsended { get; set; }
        public string Appointingbody { get; set; }
    }
}
