//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edubase.Import
{
    using System;
    using System.Collections.Generic;
    
    public partial class Governors
    {
        public int autoid { get; set; }
        public string GID { get; set; }
        public string URN { get; set; }
        public string UID { get; set; }
        public string CompaniesHouseNumber { get; set; }
        public string Deleted { get; set; }
        public string Role { get; set; }
        public string Title { get; set; }
        public string Forename1 { get; set; }
        public string Forename2 { get; set; }
        public string Surname { get; set; }
        public string Dateofappointment { get; set; }
        public string Datetermofofficeendsended { get; set; }
        public string Appointingbody { get; set; }
        public string Homepostcode { get; set; }
        public string Directemailaddress { get; set; }
        public string PreviousTitle { get; set; }
        public string PreviousForename1 { get; set; }
        public string PreviousForename2 { get; set; }
        public string PreviousSurname { get; set; }
        public string DateofBirth { get; set; }
        public string Nationality { get; set; }
    }
}
