//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edubase.Import
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupData
    {
        public int autoid { get; set; }
        public string GroupUID { get; set; }
        public string GroupID { get; set; }
        public string GroupName { get; set; }
        public string CompaniesHouseNumber { get; set; }
        public string GroupTypecode { get; set; }
        public string GroupType { get; set; }
        public string ClosedDate { get; set; }
        public string GroupStatuscode { get; set; }
        public string GroupStatus { get; set; }
        public string HeadofGroupTitle { get; set; }
        public string HeadofGroupFirstName { get; set; }
        public string HeadofGroupLastName { get; set; }
        public string Address { get; set; }
    }
}
