//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edubase.Import
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ofstedratings
    {
        public int autoid { get; set; }
        public string URN { get; set; }
        public string Inspectiondate { get; set; }
        public string Overalleffectiveness { get; set; }
        public string REPORTURL { get; set; }
    }
}
