//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edubase.Import
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolToCompanyLinks
    {
        public int id { get; set; }
        public string URN { get; set; }
        public string LinkedUID { get; set; }
        public string Joineddate { get; set; }
    }
}
