//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edubase.Import
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolsTable
    {
        public string URN { get; set; }
        public string LAcode { get; set; }
        public string LAname { get; set; }
        public string EstablishmentNumber { get; set; }
        public string EstablishmentName { get; set; }
        public string TypeOfEstablishmentcode { get; set; }
        public string TypeOfEstablishmentname { get; set; }
        public string EstablishmentStatuscode { get; set; }
        public string EstablishmentStatusname { get; set; }
        public string ReasonEstablishmentOpenedcode { get; set; }
        public string ReasonEstablishmentOpenedname { get; set; }
        public string OpenDate { get; set; }
        public string ReasonEstablishmentClosedcode { get; set; }
        public string ReasonEstablishmentClosedname { get; set; }
        public string CloseDate { get; set; }
        public string PhaseOfEducationcode { get; set; }
        public string PhaseOfEducationname { get; set; }
        public string StatutoryLowAge { get; set; }
        public string StatutoryHighAge { get; set; }
        public string Boarderscode { get; set; }
        public string Boardersname { get; set; }
        public string NurseryProvisioncode { get; set; }
        public string NurseryProvisionname { get; set; }
        public string OfficialSixthFormcode { get; set; }
        public string OfficialSixthFormname { get; set; }
        public string Gendercode { get; set; }
        public string Gendername { get; set; }
        public string ReligiousCharactercode { get; set; }
        public string ReligiousCharactername { get; set; }
        public string ReligiousEthoscode { get; set; }
        public string ReligiousEthosname { get; set; }
        public string Diocesecode { get; set; }
        public string Diocesename { get; set; }
        public string AdmissionsPolicycode { get; set; }
        public string AdmissionsPolicyname { get; set; }
        public string SchoolCapacity { get; set; }
        public string SpecialClassescode { get; set; }
        public string SpecialClassesname { get; set; }
        public string UKPRN { get; set; }
        public string LastChangedDate { get; set; }
        public string Street { get; set; }
        public string Locality { get; set; }
        public string Address3 { get; set; }
        public string Town { get; set; }
        public string Countyname { get; set; }
        public string Postcode { get; set; }
        public string SchoolWebsite { get; set; }
        public string MainEmail { get; set; }
        public string AlternativeEmail { get; set; }
        public string TelephoneNum { get; set; }
        public string HeadTitlecode { get; set; }
        public string HeadTitlename { get; set; }
        public string HeadFirstName { get; set; }
        public string HeadLastName { get; set; }
        public string HeadPreferredJobTitle { get; set; }
    }
}
