# This is a basic workflow to help you get started with Actions

name: gitleaks

# Controls when the action will run. Triggers the workflow on push or pull request
# events for all branches
on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
      with: 
        config-path: gitleaks.config
